name       : lash
version    : 0.5.4
release    : 1
source     :
    - http://download.savannah.gnu.org/releases/lash/lash-0.5.4.tar.gz : 105a7da84415c4725c6bcad28e70f23aeb4534f94fc80ca262b6a2cef2226c16
license    : GPL-2.0 
component  : multimedia 
summary    : Session management system for GNU/Linux audio applications 
description: |
    LASH is a session management system for GNU/Linux audio applications. It allows you to save and restore audio sessions consisting of multiple interconneced applications, restoring program state (ie loaded patches) and the connections between them.
builddeps  :
    - pkgconfig(jack)
    - pkgconfig(alsa)
    - pkgconfig(libxml-2.0)
    - pkgconfig(gtk+-2.0)
setup      : |
    %patch -p1 < $pkgfiles/lash-gcc44.patch
    %patch -p1 < $pkgfiles/lash-implicit-fortify-decl.patch
    %patch < $pkgfiles/lash-swig-2x.patch
    %patch < $pkgfiles/lash-add-needed.patch
    %patch -p1 < $pkgfiles/lash-resource.patch
    %patch -p1 < $pkgfiles/lash-glibc-2.22.patch
    %configure
build      : |
    %make 
install    : |
    %make_install
