name       : lash
version    : 0.5.4
release    : 10
source     :
    - http://download.savannah.gnu.org/releases/lash/lash-0.5.4.tar.gz : 105a7da84415c4725c6bcad28e70f23aeb4534f94fc80ca262b6a2cef2226c16
license    : GPL-2.0-or-later
component  : multimedia
summary    : Session management system for GNU/Linux audio applications
description: |
    LASH is a session management system for GNU/Linux audio applications. It allows you to save and restore audio sessions consisting of multiple interconneced applications, restoring program state (ie loaded patches) and the connections between them.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(libxml-2.0)
setup      : |
    %apply_patches
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # empty python2.7 dir
    rm -r $installdir/usr/lib
